import { useEffect, useState, useRef } from "react";
import { apiFetch } from "../lib/api";

const MAPS_KEY = "AIzaSyD77yl0_MV4lnaax5oko7kg_ouls224cYA";
const HBR_LAT = 13.0358;
const HBR_LNG = 77.6200;

function Toast({msg, onClose}:{msg:string; onClose:()=>void}){
  useEffect(()=>{ const t=setTimeout(onClose,4000); return()=>clearTimeout(t); },[]);
  return (
    <div className="fixed top-[72px] right-6 z-50 bg-[#0F2440] text-white px-5 py-3 rounded-2xl shadow-2xl text-sm flex items-center gap-3 animate-bounce">
      <span>✅</span><span>{msg}</span>
      <button onClick={onClose} className="ml-2 opacity-60 hover:opacity-100">✕</button>
    </div>
  );
}

export default function Dashboard(){
  const [data,setData]=useState<any>(null);
  const [reqs,setReqs]=useState<any[]>([]);
  const [premiums,setPremiums]=useState<any[]>([]);
  const [selected,setSelected]=useState<any>(null);
  const [stage,setStage]=useState("");
  const [toast,setToast]=useState("");
  const [stageBusy,setStageBusy]=useState(false);
  const [premBusy,setPremBusy]=useState<string|null>(null);
  const [directive,setDirective]=useState("");
  const dirRef = useRef<HTMLTextAreaElement>(null);

  useEffect(()=>{
    apiFetch("/api/portal/dashboard").then(r=>setData(r.data));
    apiFetch("/api/client-requests").then(r=>setReqs(r.data||[]));
    apiFetch("/api/premium-applications").then(r=>setPremiums(r.data||[]));
    apiFetch("/api/directives/today").then(r=>{ if(r.data?.message) setDirective(r.data.message); });
  },[]);

  const showToast=(msg:string)=>{ setToast(msg); };

  const updateStage = async()=>{
    if(!selected || !stage) return;
    setStageBusy(true);
    const r = await apiFetch(`/api/client-requests/${selected.id}/stage`, {method:"PATCH", body: JSON.stringify({stage})});
    setStageBusy(false);
    if(r.success){
      setReqs(reqs.map(x=>x.id===selected.id? r.data : x));
      setSelected(r.data);
      setStage("");
      showToast(`✅ Request ${r.data.reference} moved to ${stage}`);
    } else {
      showToast("❌ Stage update failed: " + (r.error||"unknown"));
    }
  };

  const updatePremium = async(id:string, status:string)=>{
    setPremBusy(id+status);
    const r = await apiFetch(`/api/premium-applications/${id}/status`,{method:"PATCH", body:JSON.stringify({status})});
    setPremBusy(null);
    if(r.success){
      setPremiums(prev=>prev.map(x=>x.id===id?r.data:x));
      showToast(`Application ${r.data.referenceNo} → ${status}`);
    }
  };

  const exportDossier = ()=>{
    if(!selected) return;
    const html=`<!DOCTYPE html><html><head><title>Dossier ${selected.reference}</title>
      <style>body{font-family:Arial;padding:32px;color:#0F2440}h2{color:#0F2440}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left}.badge{display:inline-block;padding:2px 10px;border-radius:999px;font-size:12px;background:#FEF3C7;color:#92400E}</style></head>
      <body><h2>PEES Tee Group Pvt Ltd</h2><p>HBR Layout, Bengaluru – 560043</p><hr/>
      <h3>Client Request Dossier</h3>
      <table><tr><th>Field</th><th>Value</th></tr>
      <tr><td>Reference</td><td><b>${selected.reference}</b></td></tr>
      <tr><td>Service</td><td>${selected.serviceType}</td></tr>
      <tr><td>Description</td><td>${selected.description}</td></tr>
      <tr><td>Contact Time</td><td>${selected.preferredContactTime||"—"}</td></tr>
      <tr><td>Current Stage</td><td><span class="badge">${selected.stage}</span></td></tr>
      <tr><td>Created</td><td>${new Date(selected.createdAt).toLocaleString()}</td></tr></table>
      <h4 style="margin-top:20px">Milestone Timeline</h4>
      ${selected.stageHistory.map((h:any)=>`<p>▶ <b>${h.stage}</b> — ${new Date(h.at).toLocaleString()}</p>`).join("")}
      <p style="margin-top:32px;color:#94A3B8;font-size:12px">Generated by PEES Tee Portal on ${new Date().toLocaleString()}</p>
      </body></html>`;
    const w=window.open("","_blank");
    w?.document.write(html);
    w?.document.close();
    w?.print();
  };

  const publishDirective=async()=>{
    const msg = dirRef.current?.value || directive;
    if(!msg.trim()){ alert("Please enter a directive message."); return; }
    const r=await apiFetch("/api/directives",{method:"POST", body: JSON.stringify({message: msg, createdBy:"admin"})});
    if(r.success) showToast("Directive published — field app will show on next first login");
  };

  const KPI_COLORS = ["#E0E7FF","#FEF3C7","#DCFCE7","#FCE7F3"];

  return (
    <div className="space-y-6">
      {toast && <Toast msg={toast} onClose={()=>setToast("")}/>}

      {/* KPI Cards */}
      <div className="grid grid-cols-4 gap-4">
        {[
          ["Total Requests", data?.totalRequests ?? "—", "📋"],
          ["Pending KYC", data?.pendingPremium ?? "—", "📄"],
          ["Active Field Staff", data?.activeField ?? "—", "🟢"],
          ["Leaves Pending", data?.leavesPending ?? "—", "📅"],
        ].map(([k,v,icon],i)=>(
          <div key={String(k)} className="bg-white rounded-2xl p-5 shadow-sm border" style={{borderLeft:`4px solid ${["#6366F1","#F59E0B","#10B981","#EC4899"][i]}`}}>
            <div className="flex justify-between items-start"><div className="text-sm text-slate-500">{k}</div><span className="text-xl">{icon}</span></div>
            <div className="text-3xl font-extrabold text-[#0F2440] mt-2">{String(v)}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-3 gap-6">
        {/* Client Requests Table */}
        <div className="col-span-2 bg-white rounded-2xl border shadow-sm">
          <div className="p-5 border-b flex justify-between items-center">
            <h3 className="font-bold text-[#0F2440]">Client Requests — Stage Board</h3>
            <span className="text-xs bg-[#F1F5F9] px-3 py-1 rounded-full">Live • {reqs.length} total</span>
          </div>
          <div className="overflow-auto">
            <table className="w-full text-sm">
              <thead className="text-xs text-slate-500 bg-slate-50">
                <tr><th className="text-left p-3">Ref</th><th className="text-left">Service</th><th>Stage</th><th>Updated</th><th></th></tr>
              </thead>
              <tbody>
                {reqs.map(r=>(
                  <tr key={r.id} className="border-t hover:bg-slate-50 transition-colors">
                    <td className="p-3 font-mono text-[#0F2440] font-bold">{r.reference}</td>
                    <td className="text-slate-600">{r.serviceType}</td>
                    <td className="text-center"><span className={`px-2.5 py-1 rounded-full text-xs font-bold ${r.stage==="APPLIED"?"bg-slate-100 text-slate-600": r.stage==="CONNECTED"?"bg-blue-50 text-blue-600": r.stage==="IN_PROCESSING"?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700"}`}>{r.stage.replace("_"," ")}</span></td>
                    <td className="text-xs text-slate-500">{new Date(r.updatedAt).toLocaleString()}</td>
                    <td className="p-2"><button onClick={()=>{setSelected(r);setStage("");}} className="px-3 py-1.5 rounded-xl bg-[#0F2440] text-white text-xs hover:bg-[#1a3a6b] transition-colors">Preview</button></td>
                  </tr>
                ))}
                {reqs.length===0 && <tr><td colSpan={5} className="p-6 text-center text-slate-400">No requests yet</td></tr>}
              </tbody>
            </table>
          </div>
        </div>

        {/* Premium Applications */}
        <div className="bg-white rounded-2xl border shadow-sm">
          <div className="p-5 border-b"><h3 className="font-bold text-[#0F2440]">Premium Applications</h3><p className="text-xs text-slate-500">Approve / Reject / Flag</p></div>
          <div className="p-3 space-y-3 max-h-[420px] overflow-auto">
            {premiums.map(p=>(
              <div key={p.id} className="border rounded-xl p-3">
                <div className="flex justify-between"><span className="font-mono font-bold text-[#0F2440]">{p.referenceNo}</span><span className={`text-xs px-2 py-1 rounded-full ${p.status==="PENDING_REVIEW"?"bg-amber-100 text-amber-700": p.status==="APPROVED"?"bg-emerald-100 text-emerald-700":"bg-red-100 text-red-600"}`}>{p.status.replace("_"," ")}</span></div>
                <div className="text-sm mt-1 text-slate-600">{p.clientName} • {p.paymentMode} • <span className={p.paymentStatus==="SUCCESSFUL"?"text-emerald-600 font-bold":"text-amber-600"}>{p.paymentStatus}</span></div>
                {p.status==="PENDING_REVIEW" && (
                  <div className="flex gap-2 mt-2">
                    <button disabled={premBusy===p.id+"APPROVED"} onClick={()=>updatePremium(p.id,"APPROVED")} className="flex-1 py-1.5 rounded-lg bg-emerald-600 text-white text-xs disabled:opacity-50">
                      {premBusy===p.id+"APPROVED"?"…":"Approve"}
                    </button>
                    <button disabled={premBusy===p.id+"REJECTED"} onClick={()=>updatePremium(p.id,"REJECTED")} className="flex-1 py-1.5 rounded-lg border text-xs disabled:opacity-50">
                      {premBusy===p.id+"REJECTED"?"…":"Reject"}
                    </button>
                  </div>
                )}
              </div>
            ))}
            {premiums.length===0 && <p className="text-slate-400 text-sm text-center py-4">No applications yet</p>}
          </div>
        </div>
      </div>

      {/* HR & Ops Row */}
      <div className="grid grid-cols-3 gap-6">
        <div className="bg-white rounded-2xl border p-5 shadow-sm">
          <h4 className="font-bold text-[#0F2440]">Daily Performance Audit</h4>
          <div className="mt-3 space-y-2 text-sm">
            {(data?.perEmployee||[]).slice(0,5).map((e:any)=>(
              <div key={e.id} className="flex justify-between border-b py-2 last:border-0">
                <span>{e.name} <span className="text-xs text-slate-500">({e.role})</span></span>
                <span className="font-bold text-slate-700">{e.requestsHandled} handled • <span className={e.punctuality>=95?"text-emerald-600":e.punctuality>=90?"text-amber-600":"text-red-500"}>{e.punctuality}%</span></span>
              </div>
            ))}
          </div>
        </div>

        {/* Live Map — Google Maps Embed */}
        <div className="bg-white rounded-2xl border p-5 shadow-sm">
          <h4 className="font-bold text-[#0F2440]">Live Map — Field Tracking</h4>
          <div className="mt-3 rounded-xl overflow-hidden border" style={{height:220}}>
            <iframe
              title="Live Field Map"
              width="100%" height="220"
              style={{border:0}}
              loading="lazy"
              referrerPolicy="no-referrer-when-downgrade"
              src={`https://www.google.com/maps/embed/v1/place?key=${MAPS_KEY}&q=HBR+Layout,Bengaluru,Karnataka&zoom=14&maptype=roadmap`}
            />
          </div>
          <div className="text-xs text-slate-500 mt-2">📍 HBR Layout HO • Real-time markers via WebSocket in production</div>
        </div>

        {/* Shift Directives */}
        <div className="bg-white rounded-2xl border p-5 shadow-sm">
          <h4 className="font-bold text-[#0F2440]">Shift-Start Directives</h4>
          <textarea
            ref={dirRef}
            value={directive}
            onChange={e=>setDirective(e.target.value)}
            placeholder="Message for first login of the day..."
            className="w-full border rounded-xl p-3 mt-3 text-sm h-[120px] focus:outline-none focus:ring-2 focus:ring-[#C6A664] resize-none"
          />
          <button
            onClick={publishDirective}
            className="w-full mt-3 py-2.5 rounded-xl bg-[#C6A664] font-bold text-[#0F2440] hover:bg-[#b8973d] transition-colors"
          >Publish Directive</button>
          <p className="text-xs text-slate-500 mt-2">Shown as modal popup on employee first login of the day.</p>
        </div>
      </div>

      {/* Preview Modal */}
      {selected && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center p-6 z-40" onClick={()=>setSelected(null)}>
          <div className="bg-white rounded-2xl max-w-3xl w-full overflow-hidden shadow-2xl" onClick={e=>e.stopPropagation()}>
            <div className="p-6 border-b flex justify-between items-center">
              <div>
                <h3 className="font-bold text-[#0F2440]">Client Preview — {selected.reference}</h3>
                <p className="text-xs text-slate-500">{selected.serviceType}</p>
              </div>
              <button onClick={()=>setSelected(null)} className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center hover:bg-slate-200">✕</button>
            </div>
            <div className="p-6 grid grid-cols-2 gap-6">
              <div className="space-y-3 text-sm">
                <div><span className="text-slate-500">Service:</span> <b>{selected.serviceType}</b></div>
                <div><span className="text-slate-500">Description:</span> {selected.description}</div>
                <div><span className="text-slate-500">Contact time:</span> {selected.preferredContactTime||"—"}</div>
                <div className="flex gap-2 mt-3">
                  <select value={stage} onChange={e=>setStage(e.target.value)} className="border rounded-xl px-3 py-2 text-sm flex-1 focus:outline-none focus:ring-2 focus:ring-[#0F2440]">
                    <option value="">Move stage...</option>
                    <option>APPLIED</option><option>CONNECTED</option><option>IN_PROCESSING</option><option>COMPLETED</option>
                  </select>
                  <button disabled={!stage||stageBusy} onClick={updateStage} className="px-4 py-2 rounded-xl bg-[#0F2440] text-white text-sm disabled:opacity-50 hover:bg-[#1a3a6b] transition-colors">
                    {stageBusy?"Updating…":"Update"}
                  </button>
                </div>
                <button onClick={exportDossier} className="w-full mt-2 py-2 rounded-xl border font-semibold text-sm hover:bg-slate-50 transition-colors">⬇ Export PDF Dossier</button>
              </div>
              <div>
                <div className="font-semibold text-sm mb-2">Milestone Timeline</div>
                <div className="space-y-2">
                  {selected.stageHistory.map((h:any,i:number)=>(
                    <div key={i} className="flex gap-3 text-sm">
                      <div className="w-2 h-2 rounded-full bg-[#C6A664] mt-2 shrink-0"/>
                      <div><div className="font-semibold">{h.stage.replace("_"," ")}</div><div className="text-xs text-slate-500">{new Date(h.at).toLocaleString()}</div></div>
                    </div>
                  ))}
                </div>
                <div className="mt-4 bg-[#F8FAFC] rounded-xl p-3 text-xs text-slate-500">
                  <span className="font-semibold block">Attachments</span>
                  {selected.attachments?.length ? selected.attachments.map((a:any,i:number)=><div key={i}>📎 {a.name}</div>) : "No attachments on this request"}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
