import { useEffect, useState } from "react";
import { apiFetch } from "../lib/api";

export default function Reports(){
  const [reports,setReports]=useState<any[]>([]);
  const [activities,setActivities]=useState("");
  const [collections,setCollections]=useState("");
  const [notes,setNotes]=useState("");
  const [busy,setBusy]=useState(false);
  const [toast,setToast]=useState("");
  const showToast=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),4000);};

  useEffect(()=>{apiFetch("/api/eod-reports").then(r=>setReports(r.data||[]));},[]);

  const submit=async()=>{
    if(!activities.trim()){showToast("Activities field is required");return;}
    setBusy(true);
    const r=await apiFetch("/api/eod-reports",{method:"POST",body:JSON.stringify({activities:activities.trim(),collections:collections.trim()||"Nil",notes:notes.trim()||"—",employeeId:"u_admin"})});
    setBusy(false);
    if(r.success){setReports(x=>[r.data,...x]);setActivities("");setCollections("");setNotes("");showToast("EOD Report submitted");}
  };

  const printReport=(rep:any)=>{
    const html = `<!DOCTYPE html><html><head><title>EOD Report ${rep.date}</title><style>body{font-family:Arial;padding:32px;color:#0F2440}h2{color:#0F2440}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px}</style></head>
    <body><h2>PEES Tee Group Pvt Ltd</h2><p>EOD Field Report — ${rep.date}</p><hr/>
    <table><tr><th>Field</th><th>Detail</th></tr>
    <tr><td>Employee</td><td>${rep.employeeId}</td></tr>
    <tr><td>Activities</td><td>${rep.activities}</td></tr>
    <tr><td>Collections</td><td>${rep.collections}</td></tr>
    <tr><td>Notes</td><td>${rep.notes}</td></tr>
    <tr><td>Submitted</td><td>${new Date(rep.createdAt).toLocaleString()}</td></tr></table>
    <p style="color:#94A3B8;font-size:12px;margin-top:24px">Generated by PEES Tee Portal on ${new Date().toLocaleString()}</p>
    </body></html>`;
    const w=window.open("","_blank"); w?.document.write(html); w?.document.close(); w?.print();
  };

  return (
    <div className="space-y-6">
      {toast&&<div className="fixed top-[72px] right-6 z-50 bg-[#0F2440] text-white px-5 py-3 rounded-2xl shadow-xl text-sm">{toast}</div>}
      <div><h2 className="text-xl font-extrabold text-[#0F2440]">Reports — EOD Field Reports</h2><p className="text-sm text-slate-500">Daily end-of-day summary from field employees</p></div>

      <div className="bg-white rounded-2xl border shadow-sm p-5">
        <h3 className="font-bold text-[#0F2440] mb-4">Submit EOD Report (Admin / Demo)</h3>
        <div className="space-y-3">
          <textarea value={activities} onChange={e=>setActivities(e.target.value)} placeholder="Activities completed today *" className="w-full border rounded-xl p-3 text-sm h-[80px] focus:outline-none focus:ring-2 focus:ring-[#C6A664] resize-none"/>
          <input value={collections} onChange={e=>setCollections(e.target.value)} placeholder="Collections / payments received (if any)" className="w-full border rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#C6A664]"/>
          <textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Any additional notes..." className="w-full border rounded-xl p-3 text-sm h-[60px] focus:outline-none focus:ring-2 focus:ring-[#C6A664] resize-none"/>
          <button disabled={busy} onClick={submit} className="w-full py-2.5 rounded-xl bg-[#C6A664] font-bold text-[#0F2440] hover:bg-[#b8973d] disabled:opacity-50 transition-colors">
            {busy?"Submitting…":"Submit EOD Report"}
          </button>
        </div>
      </div>

      <div className="bg-white rounded-2xl border shadow-sm">
        <div className="p-5 border-b"><h3 className="font-bold text-[#0F2440]">EOD Report History ({reports.length})</h3></div>
        <div className="divide-y">
          {reports.map(r=>(
            <div key={r.id} className="p-5 hover:bg-slate-50 transition-colors">
              <div className="flex justify-between items-start">
                <div><div className="font-semibold text-[#0F2440]">{r.date}</div><div className="text-xs text-slate-500">by {r.employeeId} • {new Date(r.createdAt).toLocaleString()}</div></div>
                <button onClick={()=>printReport(r)} className="px-3 py-1 rounded-lg border text-xs font-semibold hover:bg-slate-100 transition-colors">🖨 Print</button>
              </div>
              <div className="mt-2 grid grid-cols-3 gap-3 text-sm">
                <div><span className="text-slate-500">Activities:</span><p>{r.activities}</p></div>
                <div><span className="text-slate-500">Collections:</span><p>{r.collections}</p></div>
                <div><span className="text-slate-500">Notes:</span><p>{r.notes}</p></div>
              </div>
            </div>
          ))}
          {reports.length===0&&<div className="p-6 text-center text-slate-400">No reports submitted yet</div>}
        </div>
      </div>
    </div>
  );
}
